### ISSUE TITLE
no binary release

### ISSUE THREAD

**Issue by Darin755** [kawilkins/TemperatureMonitor#1]
Can you add a binary release? It would be very helpful if I didn't have to compile it. You should be able to add it directly to github releases.

**Comment by kawilkins** [comment]
Thank you for contacting me.

I will be taking care of the release soon.

⁣Kevin Wilkins
***@***.***

Sent from my Pixel 6

Get BlueMail for Android ​

**Comment by kawilkins** [comment]
I have created the first release.
I am closing this issue.
